# This file has been generated by node2nix 1.9.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {};
in
{
  flood = nodeEnv.buildNodePackage {
    name = "flood";
    packageName = "flood";
    version = "4.7.0";
    src = fetchurl {
      url = "https://registry.npmjs.org/flood/-/flood-4.7.0.tgz";
      sha512 = "MAm4Yok64VPa49DM+0TxBBP0mScW5ILGCsY/HJLbATjHEkJFnwD1mkPndruZxO1vXBaFdPzoLl+gYThAUxWQjA==";
    };
    buildInputs = globalBuildInputs;
    meta = {
      description = "A modern Web UI for various torrent clients with multi-user and multi-client support";
      homepage = "https://github.com/jesec/flood#readme";
      license = "GPL-3.0-only";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
}
